### ISSUE TITLE
Pretrained models to reproduce paper's results

### ISSUE THREAD

**Issue by NahyukLEE** [Wuziyi616/multi_part_assembly#1]
Thank you for your great work and dataset!

I tried to reproduce Global/DGL/LSTM results for `everyday` subset(2~20 frags), with same experiment settings, but I had quite different results on some metrics. I had almost same results on RMSE(Trans.), PA(Part Accuracy), but cannot on others(RMSE(Rot.), CD).
![image](https://user-images.githubusercontent.com/51054576/195517306-d491b8c3-8575-4de3-a793-f2fb0f07c964.png)

Do you have any plan to share your pretrained model that can reproduce results in paper(breaking-bad)?
If you can, I will very appreciate with that.

Thanks.

**Comment by Wuziyi616** [comment]
Hi, thank you for your interest in our work. Your results are definitely correct, because we discovered there are 2 bugs in our original eval code:
- One is in Rotation, we handled the 2\pi symmetry in a wrong way. That's why you get better results (smaller RMSE now)
- Another one is in CD, see [here](https://github.com/Wuziyi616/multi_part_assembly/blob/bad96211b737637dd16c203264a606180d17c75e/multi_part_assembly/models/modules/base_model.py#L273) for explanations. Basically, in our modified version of the code, we divide the CD by the true number of parts of each shape, instead of the padded number (20, which is done in DGL). This is because we have an ablation study on different numbers of input parts, so if we divide by the padded number, then the CD for 100 parts will be better than 20 parts (in fact 100 parts is much worse)

And we also updated these results in our [camera-ready](https://openreview.net/pdf?id=mJWt6pOcHNy) by re-running all the benchmark experiments, which is uploaded to openreview yesterday. You can take a look at our new Table 3. The results are very similar to what you obtained.

**Comment by Wuziyi616** [comment]
Though the numbers change after correcting the code, the trend of the results is the same, e.g. DGL still performs the best. So we don't change the observations/conclusions drawn from the experiments

**Comment by Wuziyi616** [comment]
@NahyukLEE let me know if you have further questions, or if you don't mind closing the issue. Thanks!

**Comment by NahyukLEE** [comment]
Thank you for your detail comments! I checked your camera-ready paper.
