### ISSUE TITLE
May I suggest a more general library for saving point clouds, other than open3d?

### ISSUE THREAD

**Issue by Ruiyuan-Zhang** [Wuziyi616/multi_part_assembly#10]
Hi,

[Open3d](https://github.com/isl-org/Open3D) is only for `Ubuntu 18.04+`, `macOS 10.15+`, and `Windows 10+ (64-bit)`.

So, some CentOS users like me cannot use this library normally. In order to better amplify the impact of your work, I highly recommend you use some other more general library.

( You only need to fix [there](https://github.com/Wuziyi616/multi_part_assembly/blob/d874cb202c91b936eb712a2e983b248a882caa78/multi_part_assembly/utils/utils.py#L36).  :)

Thanks.

**Comment by Wuziyi616** [comment]
Thanks for your great suggestion! Do you have any recommended packages for saving point cloud? I use open3d simply because its saving function is very easy. Also if that's just one function of change, do you mind modifying it on your side and creating a PR to this repo? I can review and merge it then. Also, we need to fix the requirements [here](https://github.com/Wuziyi616/multi_part_assembly/blob/d874cb202c91b936eb712a2e983b248a882caa78/setup.py#L5)

**Comment by Ruiyuan-Zhang** [comment]
Hi, I have finished it [here](https://github.com/Wuziyi616/multi_part_assembly/pull/11).
![image](https://user-images.githubusercontent.com/71813586/231052165-bb6f7ab0-6614-4665-89a0-6325bdff3ef5.png)

**Comment by Wuziyi616** [comment]
Thanks for your contribution! The PR is merged. I just wanna make sure, the modified code works on your side right (i.e. it is able to save a point cloud to a ply or obj file)?

**Comment by Ruiyuan-Zhang** [comment]
I have tested the code on my machine and I am confident that the PR will work. 
It is capable of saving a ply file as shown below.
![image](https://user-images.githubusercontent.com/71813586/231227536-1f2762b7-75e9-4c7f-80b7-dab468824412.png)
