### ISSUE TITLE
Is it possible to have text description of the object

### ISSUE THREAD

**Issue by yayati29** [Wuziyi616/multi_part_assembly#15]
Since the data everyday object dataset is taken from partnet. Is it possible to also have a file with model id and text description of the model.

**Comment by Wuziyi616** [comment]
Since we save the data under the original naming (e.g. `Bottle/7b1fc86844257f8fa54fd40ef3a8dfd0`), I believe it's possible to retrieve the text descriptions from the original ShapeNet dataset. You need to map the category name `Bottle` to the original folder name (I believe it should be matched to `02876657`).
