### ISSUE TITLE
A bug in line 264 of base_model.py

### ISSUE THREAD

**Issue by yaorz97** [Wuziyi616/multi_part_assembly#7]
The outputs of function `shape_cd_loss` should be ` transform_pt_cd_loss,  pred_trans_pts, gt_trans_pts`

**Comment by Wuziyi616** [comment]
Hi, thanks for pointing that out. It's fixed in the latest commit. This bug have no effect on the benchmark results, because neither the variables are used in the code.

However, this could be the reason why in my early experiments, adding an adversarial loss doesn't help the performance... I was inputting the GT- instead of the predicted- transformed shapes into the discriminator...
