### ISSUE TITLE
Unbroken models

### ISSUE THREAD

**Issue by yaorz97** [Wuziyi616/multi_part_assembly#8]
Hi, I want to know how to obtain the mesh files of unbroken models.  If we directly merge all the fractures together, there will be a lot of faces on the fracture surface.

**Comment by Wuziyi616** [comment]
@YunChunChen pining my teammate on this. IIRC we use the object name as the directory name of broken parts. So there should be a way to find the original 3D model. But we cannot share the original data due to license issue. So probably you have to download those datasets (PartNet and Thingi10K) and retrieve from them.

**Comment by YunChunChen** [comment]
You can get the original mesh file name by parsing the folder name. For example, if the folder name is `everyday/Bottle/7984d4980d5b07bceba393d429f71de3/`, then the original mesh file should be something like  `Bottle/7984d4980d5b07bceba393d429f71de3.obj`

**Comment by Wuziyi616** [comment]
I think we're actually using a variant of PartNet right? From a robotics grasping dataset called [ACRONYM](https://arxiv.org/abs/2011.09584). This is because the shapes in this dataset are aligned to a canonical pose.

For Thingi10K it's a bit complicated, you should go to their [webpage](https://ten-thousand-models.appspot.com/) and search for the object id. For example, you can get the original of `artifact/39087_sf/` by searching for `id=39087_sf` on the website. I believe they have API or script for batch automatic downloading.

**Comment by Wuziyi616** [comment]
Feel free to re-open the issue if you have any further questions :)

**Comment by yaorz97** [comment]
Thank you for the valuable information. However I still have some doubts, if I want to get the original mesh files of the EVERYDAY dataset, should I just download the PartNet dataset? I find that PartNet offers three versions(datav0,  sem_seg_h5, and ins_seg_h5), which one should I download?

**Comment by Wuziyi616** [comment]
We use a PartNet variant called [ACRONYM](https://sites.google.com/nvidia.com/graspdataset). You probably have to download it. I currently don't have access to this original dataset on the cluster, so I cannot confirm if the ID is exactly the same or under some naming conversion. But I think they should be the same.
